package com.goddoro.youtubeplayer

object CommonConst {

    const val ACTION_PLAYER_PAUSE = "MYK_ACTION_PLAYER_PAUSE"
    const val ACTION_PLAYER_STOP = "MYK_ACTION_PLAYER_STOP"
    const val ACTION_PLAYER_PLAY = "MYK_ACTION_PLAYER_PLAY"
    const val ACTION_PLAYER_PREV = "MYK_PLAYER_PREV"
    const val ACTION_PLAYER_NEXT = "MYK_PLAYER_NEXT"
    const val ACTION_PLAYER_TEN_PREV = "MYK_PLAYER_TEN_PREV"
    const val ACTION_PLAYER_TEN_NEXT = "MYK_PLAYER_TEN_NEXT"
    const val ACTION_PLAYER_CLOSE = "MYK_PLAYER_CLOSE"
    const val ACTION_PLAYER_STOP_TV = "MYK_PLAYER_STOP_TV"
    const val ACTION_PLAYER_STOP_RADIO = "MYK_PLAYER_STOP_RADIO"

    const val PAUSE_INTENT_REQUEST = 11
    const val PLAY_INTENT_REQUEST = 12
    const val CLOSE_INTENT_REQUEST = 13
    const val PREV_INTENT_REQUEST = 14
    const val NEXT_INTENT_REQUEST = 15
    const val TEN_SECOND_PREV_INTENT_REQUEST = 16
    const val TEN_SECOND_NEXT_INTENT_REQUEST = 17
    const val CONTENT_INTENT_REQUEST = 18
}